const initialState = {
  cityName: 'Blumenau',
  cityCode: '35954',
  current: {
    date: '2022-07-07T14:20:00-03:00',
    temp: 29,
    icon: 7,
    iconPhrase: 'Nublado',
    hasPrecipitation: false,
    precipitaionType: null,
    isDayTime: true,
  },
  dailyForecast: [
    {
      date: '2022-07-07T07:00:00-03:00',
      minTemp: 9,
      maxTemp: 30,
      day: {
        icon: 7,
        iconPhrase: 'Nublado',
        hasPrecipitation: false,
        precipitaionType: null,
        precipitaionIntensity: null,
      },
      night: {
        icon: 34,
        iconPhrase: 'Predominantemente aberto',
        hasPrecipitation: false,
        precipitaionType: null,
        precipitaionIntensity: null,
      },
    },
    {
      date: '2022-07-08T07:00:00-03:00',
      minTemp: 14,
      maxTemp: 26,
      day: {
        icon: 4,
        iconPhrase: 'Nuvens esparsas',
        hasPrecipitation: false,
        precipitaionType: null,
        precipitaionIntensity: null,
      },
      night: {
        icon: 12,
        iconPhrase: 'Pancadas de chuva',
        hasPrecipitation: true,
        precipitaionType: 'Rain',
        precipitaionIntensity: 'Light',
      },
    },
    {
      date: '2022-07-09T07:00:00-03:00',
      minTemp: 14,
      maxTemp: 26,
      day: {
        icon: 4,
        iconPhrase: 'Nuvens esparsas',
        hasPrecipitation: false,
        precipitaionType: null,
        precipitaionIntensity: null,
      },
      night: {
        icon: 12,
        iconPhrase: 'Pancadas de chuva',
        hasPrecipitation: true,
        precipitaionType: 'Rain',
        precipitaionIntensity: 'Light',
      },
    },
    {
      date: '2022-07-10T07:00:00-03:00',
      minTemp: 14,
      maxTemp: 26,
      day: {
        icon: 4,
        iconPhrase: 'Nuvens esparsas',
        hasPrecipitation: false,
        precipitaionType: null,
        precipitaionIntensity: null,
      },
      night: {
        icon: 12,
        iconPhrase: 'Pancadas de chuva',
        hasPrecipitation: true,
        precipitaionType: 'Rain',
        precipitaionIntensity: 'Light',
      },
    },
    {
      date: '2022-07-11T07:00:00-03:00',
      minTemp: 14,
      maxTemp: 26,
      day: {
        icon: 4,
        iconPhrase: 'Nuvens esparsas',
        hasPrecipitation: false,
        precipitaionType: null,
        precipitaionIntensity: null,
      },
      night: {
        icon: 12,
        iconPhrase: 'Pancadas de chuva',
        hasPrecipitation: true,
        precipitaionType: 'Rain',
        precipitaionIntensity: 'Light',
      },
    },
  ],

  hourly12Forecast: [
    {
      date: '2022-07-07T13:00:00-03:00',
      icon: 7,
      iconPhrase: 'Nublado',
      hasPrecipitation: false,
      isDaylight: true,
      temp: 25,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T12:00:00-03:00',
      icon: 7,
      iconPhrase: 'Nublado',
      hasPrecipitation: false,
      isDaylight: true,
      temp: 24,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T14:00:00-03:00',
      icon: 7,
      iconPhrase: 'Nublado',
      hasPrecipitation: false,
      isDaylight: true,
      temp: 26,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T15:00:00-03:00',
      icon: 7,
      iconPhrase: 'Nublado',
      hasPrecipitation: false,
      isDaylight: true,
      temp: 26,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T16:00:00-03:00',
      icon: 7,
      iconPhrase: 'Nublado',
      hasPrecipitation: false,
      isDaylight: true,
      temp: 25,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T17:00:00-03:00',
      icon: 7,
      iconPhrase: 'Nublado',
      hasPrecipitation: false,
      isDaylight: true,
      temp: 24,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T18:00:00-03:00',
      icon: 7,
      iconPhrase: 'Nublado',
      hasPrecipitation: false,
      isDaylight: true,
      temp: 22,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T19:00:00-03:00',
      icon: 38,
      iconPhrase: 'Predominantemente nublado',
      hasPrecipitation: false,
      isDaylight: false,
      temp: 21,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T20:00:00-03:00',
      icon: 36,
      iconPhrase: 'Nuvens esparsas',
      hasPrecipitation: false,
      isDaylight: false,
      temp: 19,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T21:00:00-03:00',
      icon: 35,
      iconPhrase: 'Parcialmente nublado',
      hasPrecipitation: false,
      isDaylight: false,
      temp: 18,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T22:00:00-03:00',
      icon: 35,
      iconPhrase: 'Parcialmente nublado',
      hasPrecipitation: false,
      isDaylight: false,
      temp: 18,
      precipitaionProbability: 0,
    },
    {
      date: '2022-07-07T23:00:00-03:00',
      icon: 34,
      iconPhrase: 'Predominantemente aberto',
      hasPrecipitation: false,
      isDaylight: false,
      temp: 17,
      precipitaionProbability: 0,
    },
  ],
}

export { initialState }
